package novella_models.logicnovellas;

public enum Genre {
    SUPERHERO, FANTASY, SCIENCE_FICTION, HORROR, MYSTERY, ROMANCE, HISTORICAL_FICTION,
    ADVENTURE, CRIME, COMEDY, SLICE_OF_LIFE, AUTOBIOGRAPHICAL, DYSTOPIAN, COMING_OF_AGE,
    THRILLER, WESTERN, LGBTQ, STEAMPUNK, SATIRE, NOIR
}
